import type Database from "better-sqlite3";
import { z } from "zod";
import { reasoningRequestFields } from "../lib/ai/reasoning";
import { LOCAL_USER_ID } from "../storage/sqlite/database";
import { TripService } from "./trip-service";
type Vault = { decrypt(value: string | null): string };
const schema = z.object({ tripId: z.string().uuid(), prompt: z.string().trim().min(1).max(12000), useMcp: z.boolean().default(true), mode: z.enum(["conversation", "format"]).default("conversation"), responseKind: z.enum(["reply", "plan"]).default("plan"), confirmedAnswer: z.string().max(30000).optional(), conversation: z.array(z.object({ role: z.enum(["user", "assistant"]), content: z.string().max(12000) })).optional() });
const extract = (text: string) => { const clean = text.trim().replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, ""), start = clean.indexOf("{"), end = clean.lastIndexOf("}"); if (start < 0 || end < start) throw Error("AI_RESPONSE_INVALID"); return JSON.parse(clean.slice(start, end + 1)); };
export class AiService {
  constructor(private db: Database.Database, private vault: Vault, private trips: TripService) {}
  private public(row: any) { const context = JSON.parse(row.context_json || "{}"); return { id: row.id, tripId: row.trip_id, prompt: row.prompt, mode: context.mode || "conversation", status: row.status, stage: row.stage, progress: row.progress, attempts: row.attempts, activity: context.activity || [], createdAt: row.created_at, updatedAt: row.updated_at, result: row.result_json ? JSON.parse(row.result_json) : null, error: row.error }; }
  list(tripId: string) { const rows = this.db.prepare("SELECT * FROM ai_jobs WHERE user_id=? AND trip_id=? ORDER BY created_at").all(LOCAL_USER_ID, tripId) as any[]; return { job: rows.length ? this.public(rows.at(-1)) : null, history: rows.map(row => this.public(row)) }; }
  get(id: string) { const row: any = this.db.prepare("SELECT * FROM ai_jobs WHERE id=? AND user_id=?").get(id, LOCAL_USER_ID); if (!row) throw Error("NOT_FOUND"); return this.public(row); }
  create(raw: unknown) { const input = schema.parse(raw), id = crypto.randomUUID(), context = { mode: input.mode, responseKind: input.responseKind, conversation: input.conversation || [], activity: [{ kind: "system", status: "active", title: "准备本地 AI 任务" }] }; this.db.prepare("INSERT INTO ai_jobs(id,user_id,trip_id,prompt,use_mcp,status,stage,progress,context_json)VALUES(?,?,?,?,?,'queued','queued',5,?)").run(id, LOCAL_USER_ID, input.tripId, input.prompt, input.useMcp ? 1 : 0, JSON.stringify(context)); setTimeout(() => void this.run(id, input), 0); return this.get(id); }
  cancel(id: string) { this.db.prepare("UPDATE ai_jobs SET status='cancelled',stage='cancelled',updated_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=? AND status IN('queued','running')").run(id, LOCAL_USER_ID); }
  clear(tripId: string) { this.db.prepare("DELETE FROM ai_jobs WHERE user_id=? AND trip_id=?").run(LOCAL_USER_ID, tripId); }
  private async run(id: string, input: z.infer<typeof schema>) { this.db.prepare("UPDATE ai_jobs SET status='running',stage='calling_model',progress=35,attempts=attempts+1,started_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='queued'").run(id); try { const settings: any = this.db.prepare("SELECT * FROM ai_settings WHERE user_id=?").get(LOCAL_USER_ID); if (!settings?.encrypted_api_key) throw Error("AI_API_KEY_REQUIRED"); const trip = this.trips.get(input.tripId); if (!trip) throw Error("TRIP_NOT_FOUND"); const formatting = input.mode === "format", system = formatting ? `只输出 JSON {"message":"中文说明","operations":[TripOperation]}。不得改动 locked 项目。当前行程：${JSON.stringify(trip)}` : `输出 JSON {"message":"中文旅行方案","operations":[],"requiresConfirmation":true}。先讨论，未经确认不写入。当前行程：${JSON.stringify(trip)}`; const response = await fetch(String(settings.base_url).replace(/\/$/, "") + "/chat/completions", { method: "POST", headers: { authorization: `Bearer ${this.vault.decrypt(settings.encrypted_api_key)}`, "content-type": "application/json" }, body: JSON.stringify({ model: settings.model, messages: [{ role: "system", content: system }, ...(input.conversation || []), { role: "user", content: input.confirmedAnswer || input.prompt }], response_format: { type: "json_object" }, ...reasoningRequestFields(settings.model, !!settings.thinking_enabled) }), signal: AbortSignal.timeout(120000), redirect: "error" }); if (!response.ok) throw Error(`AI_REQUEST_FAILED_${response.status}`); const payload: any = await response.json(), result = extract(payload.choices?.[0]?.message?.content || ""); if (!Array.isArray(result.operations)) result.operations = []; if (!formatting) result.requiresConfirmation = true; this.db.prepare("UPDATE ai_jobs SET status='completed',stage='completed',progress=100,result_json=?,completed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status!='cancelled'").run(JSON.stringify(result), id); } catch (error) { const message = error instanceof Error ? error.message : "AI_JOB_FAILED"; this.db.prepare("UPDATE ai_jobs SET status='failed',stage='failed',error=?,completed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status!='cancelled'").run(message, id); } }
}
