import type Database from "better-sqlite3";
import { applyOperations, operationRequestSchema, operationSummary, type TripSnapshot } from "../lib/trips/operations";
import { LOCAL_USER_ID } from "../storage/sqlite/database";

const parse = (value: string | null, fallback: unknown) => value ? JSON.parse(value) : fallback;
export class TripService {
  constructor(private db: Database.Database) {}
  list() { return (this.db.prepare("SELECT * FROM trips WHERE user_id=? ORDER BY updated_at DESC").all(LOCAL_USER_ID) as any[]).map(row => ({ ...row, constraints: parse(row.constraints_json, {}) })); }
  get(id: string) {
    const trip: any = this.db.prepare("SELECT * FROM trips WHERE id=? AND user_id=?").get(id, LOCAL_USER_ID); if (!trip) return null;
    const days = this.db.prepare("SELECT * FROM trip_days WHERE trip_id=? ORDER BY day_index").all(id) as any[];
    const items = this.db.prepare("SELECT * FROM itinerary_items WHERE trip_id=? ORDER BY position").all(id) as any[];
    return { ...trip, userId: trip.user_id, startDate: trip.start_date, endDate: trip.end_date, budgetTotal: trip.budget_total, sourceType: trip.source_type, constraints: parse(trip.constraints_json, {}), days: days.map(day => ({ ...day, dayIndex: day.day_index, weather: parse(day.weather_json, null), summary: parse(day.summary_json, {}), items: items.filter(item => item.day_id === day.id).map(item => ({ ...item, dayId: item.day_id, startTime: item.start_time, durationMinutes: item.duration_minutes, locked: !!item.locked, lockTime: !!item.lock_time, sourceType: item.source_type, metadata: parse(item.metadata_json, {}) })), routes: [] })) };
  }
  create(body: any) {
    const fixed = /^\d{4}-\d{2}-\d{2}$/.test(body.startDate || "") && /^\d{4}-\d{2}-\d{2}$/.test(body.endDate || ""); if (!body.destination || (!fixed && !body.dayCount)) throw Error("TRIP_INPUT_INVALID");
    const start = fixed ? new Date(body.startDate + "T00:00:00Z") : null; const count = fixed ? Math.floor((new Date(body.endDate + "T00:00:00Z").getTime() - start!.getTime()) / 86400000) + 1 : Number(body.dayCount); if (!Number.isInteger(count) || count < 1 || count > 31) throw Error("TRIP_DATE_RANGE_INVALID");
    const id = crypto.randomUUID(), travelers = Math.max(1, Number(body.constraints?.travelers) || 1), constraints = { ...(body.constraints || {}), flexibleDates: !fixed, dayCount: count, travelers, perPersonBudget: body.perPersonBudget };
    const days = Array.from({ length: count }, (_, index) => ({ id: crypto.randomUUID(), date: start ? new Date(start.getTime() + index * 86400000).toISOString().slice(0, 10) : "", title: index === 0 ? "抵达与探索" : index === count - 1 ? "从容返程" : `第 ${index + 1} 天`, index: index + 1 }));
    this.db.transaction(() => { this.db.prepare("INSERT INTO trips(id,user_id,title,destination,start_date,end_date,budget_total,currency,constraints_json)VALUES(?,?,?,?,?,?,?,?,?)").run(id, LOCAL_USER_ID, body.title?.trim() || `${body.destination}之旅`, body.destination.trim(), fixed ? body.startDate : "", fixed ? body.endDate : "", body.perPersonBudget ? body.perPersonBudget * travelers : null, body.currency || "CNY", JSON.stringify(constraints)); const insert = this.db.prepare("INSERT INTO trip_days(id,trip_id,day_index,date,title)VALUES(?,?,?,?,?)"); days.forEach(day => insert.run(day.id, id, day.index, day.date, day.title)); this.db.prepare("INSERT INTO trip_versions(id,trip_id,revision,label,snapshot_json,created_by)VALUES(?,?,?,?,?,?)").run(crypto.randomUUID(), id, 1, "创建行程", JSON.stringify(this.get(id)), LOCAL_USER_ID); })(); return this.get(id);
  }
  update(id: string, body: any) { const current: any = this.db.prepare("SELECT revision FROM trips WHERE id=? AND user_id=?").get(id, LOCAL_USER_ID); if (!current) throw Error("NOT_FOUND"); if (current.revision !== body.revision) throw Error("REVISION_CONFLICT"); const result = this.db.prepare("UPDATE trips SET title=CASE WHEN ? IS NULL THEN title ELSE ? END,budget_total=CASE WHEN ? IS NULL THEN budget_total ELSE ? END,revision=revision+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND revision=?").run(body.title ?? null, body.title?.trim() ?? null, body.budgetTotal === undefined ? null : 1, body.budgetTotal ?? null, id, body.revision); if (!result.changes) throw Error("REVISION_CONFLICT"); return this.get(id); }
  delete(id: string) { if (!this.db.prepare("DELETE FROM trips WHERE id=? AND user_id=?").run(id, LOCAL_USER_ID).changes) throw Error("NOT_FOUND"); }
  preview(id: string, body: unknown) { const input = operationRequestSchema.parse(body), current = this.get(id) as TripSnapshot | null; if (!current) throw Error("TRIP_NOT_FOUND"); if (current.revision !== input.baseRevision) throw Error("REVISION_CONFLICT"); return { preview: applyOperations(current, input.operations), summary: operationSummary(input.operations), requiresConfirmation: true }; }
  apply(id: string, body: unknown) {
    const input = operationRequestSchema.parse(body); const prior: any = this.db.prepare("SELECT result_revision FROM trip_operations WHERE trip_id=? AND idempotency_key=?").get(id, input.idempotencyKey); if (prior?.result_revision) return { trip: this.get(id), idempotentReplay: true }; const current = this.get(id) as TripSnapshot | null; if (!current) throw Error("TRIP_NOT_FOUND"); if (current.revision !== input.baseRevision) throw Error("REVISION_CONFLICT"); const next = applyOperations(current, input.operations), summary = operationSummary(input.operations);
    this.db.transaction(() => { this.db.prepare("DELETE FROM itinerary_items WHERE trip_id=?").run(id); const insert = this.db.prepare("INSERT INTO itinerary_items(id,trip_id,day_id,type,title,start_time,duration_minutes,position,notes,locked,lock_time,source_type,cost,metadata_json)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)"); for (const day of next.days) for (const item of day.items as any[]) insert.run(item.id, id, day.id, item.type, item.title, item.startTime, item.durationMinutes, item.position, item.notes || "", item.locked ? 1 : 0, item.lockTime ? 1 : 0, item.sourceType || "user_added", item.cost ?? null, JSON.stringify(item.metadata || {})); if (!this.db.prepare("UPDATE trips SET revision=?,budget_total=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND revision=?").run(next.revision, next.budgetTotal ?? null, id, current.revision).changes) throw Error("REVISION_CONFLICT"); this.db.prepare("INSERT INTO trip_versions(id,trip_id,revision,label,snapshot_json,created_by)VALUES(?,?,?,?,?,?)").run(crypto.randomUUID(), id, next.revision, summary, JSON.stringify(next), LOCAL_USER_ID); this.db.prepare("INSERT INTO trip_operations(id,trip_id,base_revision,result_revision,status,summary,operations_json,idempotency_key,created_by)VALUES(?,?,?,?,?,?,?,?,?)").run(crypto.randomUUID(), id, current.revision, next.revision, "applied", summary, JSON.stringify(input.operations), input.idempotencyKey, LOCAL_USER_ID); })(); return { trip: this.get(id), summary };
  }
  restoreVersion(id: string, body: { versionId?: string; baseRevision?: number }) {
    const current = this.get(id) as TripSnapshot | null; if (!current) throw Error("TRIP_NOT_FOUND"); if (current.revision !== body.baseRevision) throw Error("REVISION_CONFLICT"); const row: any = this.db.prepare("SELECT * FROM trip_versions WHERE id=? AND trip_id=?").get(body.versionId || "", id); if (!row) throw Error("VERSION_NOT_FOUND"); const snapshot = JSON.parse(row.snapshot_json) as TripSnapshot, next = { ...snapshot, revision: current.revision + 1 }, label = `回退至版本 ${row.revision}`;
    this.db.transaction(() => { this.db.prepare("DELETE FROM itinerary_items WHERE trip_id=?").run(id); const insert = this.db.prepare("INSERT INTO itinerary_items(id,trip_id,day_id,type,title,start_time,duration_minutes,position,notes,locked,lock_time,source_type,cost,metadata_json)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)"); for (const day of next.days || []) for (const item of day.items as any[]) insert.run(item.id || crypto.randomUUID(), id, day.id, item.type, item.title, item.startTime, item.durationMinutes, item.position, item.notes || "", item.locked ? 1 : 0, item.lockTime ? 1 : 0, item.sourceType || "user_added", item.cost ?? null, JSON.stringify(item.metadata || {})); this.db.prepare("UPDATE trips SET revision=?,budget_total=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND revision=?").run(next.revision, next.budgetTotal ?? null, id, current.revision); this.db.prepare("INSERT INTO trip_versions(id,trip_id,revision,label,snapshot_json,created_by)VALUES(?,?,?,?,?,?)").run(crypto.randomUUID(), id, next.revision, label, JSON.stringify(next), LOCAL_USER_ID); })(); return { trip: this.get(id), summary: label };
  }
  versions(id: string) { return this.db.prepare("SELECT id,revision,label,created_at AS createdAt FROM trip_versions WHERE trip_id=? ORDER BY revision DESC").all(id); }
}
