/* eslint-disable @next/next/no-assign-module-variable */
type Context = { params: Promise<Record<string, string>> };
type Module = { GET?: (r: Request, c: Context) => Promise<Response>; POST?: (r: Request, c: Context) => Promise<Response>; PUT?: (r: Request, c: Context) => Promise<Response>; PATCH?: (r: Request, c: Context) => Promise<Response>; DELETE?: (r: Request, c: Context) => Promise<Response> };
const routes: Array<[RegExp, () => Promise<Module>]> = [
  [/^\/api\/desktop\/integrations$/, () => import("./integrations-route")],
  [/^\/api\/trips$/, () => import("../../app/api/trips/route")], [/^\/api\/trips\/(?<id>[0-9a-f-]+)$/i, () => import("../../app/api/trips/[id]/route")],
  [/^\/api\/trips\/(?<id>[0-9a-f-]+)\/operations\/preview$/i, () => import("../../app/api/trips/[id]/operations/preview/route")], [/^\/api\/trips\/(?<id>[0-9a-f-]+)\/operations\/apply$/i, () => import("../../app/api/trips/[id]/operations/apply/route")],
  [/^\/api\/trips\/(?<id>[0-9a-f-]+)\/versions$/i, () => import("../../app/api/trips/[id]/versions/route")], [/^\/api\/trips\/(?<id>[0-9a-f-]+)\/weather$/i, () => import("../../app/api/trips/[id]/weather/route")],
  [/^\/api\/ai\/settings$/, () => import("../../app/api/ai/settings/route")], [/^\/api\/ai\/dispatch$/, () => import("../../app/api/ai/dispatch/route")], [/^\/api\/ai\/chat$/, () => import("../../app/api/ai/chat/route")],
  [/^\/api\/ai\/jobs$/, () => import("../../app/api/ai/jobs/route")], [/^\/api\/ai\/jobs\/(?<id>[0-9a-f-]+)$/i, () => import("../../app/api/ai/jobs/[id]/route")], [/^\/api\/ai\/jobs\/(?<id>[0-9a-f-]+)\/advance$/i, () => import("../../app/api/ai/jobs/[id]/advance/route")],
  [/^\/api\/mcp\/servers$/, () => import("../../app/api/mcp/servers/route")], [/^\/api\/mcp\/servers\/(?<id>[\w-]+)\/tools$/, () => import("../../app/api/mcp/servers/[id]/tools/route")], [/^\/api\/mcp\/servers\/(?<id>[\w-]+)\/call$/, () => import("../../app/api/mcp/servers/[id]/call/route")], [/^\/api\/mcp\/servers\/(?<id>[\w-]+)\/test$/, () => import("../../app/api/mcp/servers/[id]/test/route")], [/^\/api\/mcp\/logs$/, () => import("../../app/api/mcp/logs/route")], [/^\/api\/user\/data$/, () => import("../../app/api/user/data/route")],
];
export async function dispatch(request: Request) { const path = new URL(request.url).pathname; if(path==="/api/desktop/preferences"){const{getSqlite}=await import("./database");const db=getSqlite();if(request.method==="GET"){const row=db.prepare("SELECT value_json FROM desktop_preferences WHERE key='travel'").get()as{value_json?:string}|undefined;return Response.json({preferences:row?.value_json?JSON.parse(row.value_json):null})}if(request.method==="PUT"){const body=await request.json();db.prepare("INSERT INTO desktop_preferences(key,value_json)VALUES('travel',?) ON CONFLICT(key) DO UPDATE SET value_json=excluded.value_json,updated_at=CURRENT_TIMESTAMP").run(JSON.stringify(body));return Response.json({ok:true})}}for (const [pattern, load] of routes) { const match = pattern.exec(path); if (!match) continue; const module = await load(), handler = module[request.method as keyof Module] as ((r: Request, c: Context) => Promise<Response>) | undefined; if (!handler) return Response.json({ error: "METHOD_NOT_ALLOWED" }, { status: 405 }); return handler(request, { params: Promise.resolve(match.groups || {}) }); } return Response.json({ error: "NOT_FOUND" }, { status: 404 }); }
